name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:v1.0.0 .

      # Step 4: Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_URL }}:v1.0.0 ${{ secrets.ECR_REPOSITORY_URL }}:v1.0.0

      # Step 5: Push the Docker image to ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:v1.0.0
