name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Log in to Amazon ECR using the prebuilt action
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build the Docker image
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # Step 6: Tag Docker image (this step is optional)
      - name: Tag Docker image
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Step 7: Push Docker image to AWS_ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


# name: Build and Push Docker Image to AWS ECR

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the code
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       # Step 2: Set up JDK 17
#       - name: Set up JDK 17
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'adopt'
#           java-version: '17'

#       # Step 3: Configure AWS credentials
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       # Step 4: Log in to Amazon ECR
#       - name: Log in to Amazon ECR
#         id: login-ecr
#         run: |
#           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URL }}
#           if [ $? -eq 0 ]; then
#             echo "Successfully logged in to Amazon ECR."
#           else
#             echo "Failed to log in to Amazon ECR."
#             exit 1
#           fi

#       # Step 5: Build the Docker image
#       - name: Build Docker image
#         run: |
#           if [ -z "${{ secrets.ECR_REPOSITORY_URL }}" ]; then
#             echo "ECR_REPOSITORY_URL is not set. Please check your repository secrets."
#             exit 1
#           fi
#           docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:latest .
#           if [ $? -eq 0 ]; then
#             echo "Docker image built successfully."
#           else
#             echo "Failed to build Docker image."
#             exit 1
#           fi

#       # Step 6: Tag Docker image
#       - name: Tag Docker image
#         run: |
#           docker tag ${{ secrets.ECR_REPOSITORY_URL }}:latest ${{ secrets.ECR_REPOSITORY_URL }}:latest
#           if [ $? -eq 0 ]; then
#             echo "Docker image tagged successfully."
#           else
#             echo "Failed to tag Docker image."
#             exit 1
#           fi

#       # Step 7: Push Docker image to AWS ECR
#       - name: Push Docker image to AWS ECR
#         run: |
#           docker push ${{ secrets.ECR_REPOSITORY_URL }}:latest
#           if [ $? -eq 0 ]; then
#             echo "Docker image pushed to AWS ECR successfully."
#           else
#             echo "Failed to push Docker image to AWS ECR."
#             exit 1
#           fi
